---
- name: install app tools
  apt:
    name:
      - python3-pip
      - libmysqlclient-dev
    state: present

- name: install virtualenv
  pip:
    name: virtualenv
    executable: pip3
    state: present

- name: create app directory
  file: path=/vagrant/financeapp state=directory mode=0755

- name: clone django app repo
  git:
    repo: "https://github.com/moelwinhein/myfinance.git"
    remote: origin
    version: master
    dest: /vagrant/financeapp/myfinance
    update: no

- name: install django app requirements
  pip:
    requirements: /vagrant/financeapp/myfinance/requirements.txt
    virtualenv: /vagrant/financeapp/venv
    virtualenv_python: python3
    state: present
