---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: verify mysql service
      command: service mysql status warn=false
      changed_when: false

    - name: verify mysql is listening on port 3306
      wait_for: port=3306 timeout=1